#
# A GitHub Action to first build Z88DK from source, then 
# build ZMTX-ZMRX.
#
# We need to build Z88DK from source because (1) it is
# not in the Ubuntu package repositories and (2) it is 
# available from z88dk.org only as a Snap, which is 
# not well supported in a docker container.
#

name: build
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build ZMTX and ZMRX CP/M 2.2. binaries, cross compiled via Z88DK.
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Clone Z88DK repository
        run: git clone --depth=1 --recursive  https://github.com/z88dk/z88dk.git
      - name: Install packages
        run: |
          sudo add-apt-repository -y ppa:vriviere/ppa
          # sudo add-apt-repository -y ppa:vriviere/arm
          sudo apt-get update
          sudo apt-get install -y bison cmake cross-mint-essential flex libxml2-dev
      - name: Display package versions
        run: |
          git --version
          make --version
          ld --version
          gcc --version
          awk -W version
          cmake --version
          m68k-atari-mint-ld --version
          m68k-atari-mint-ar --version
          m68k-atari-mint-gcc --version
      - name: Build TOS version of ZMTX.TTP and ZMRX.TTP
        run: |
          git submodule init
          git submodule update
          (cd libcmini; make)
          mkdir build
          cd build
          cmake -DCMAKE_TOOLCHAIN_FILE=../toolchain_file.txt ..
          make
      - name: Build Z88DK 
        run: |
          cd z88dk
          chmod 777 build.sh
          ./build.sh -C -p cpm
          echo `pwd`/bin >> $GITHUB_PATH
          echo "ZCCCFG=`pwd`/lib/config" >> $GITHUB_ENV
      - name: Build ZMTX.COM and ZMRX.COM
        run: |
          make -f makefile.cpm
      - uses: actions/upload-artifact@v2
        with:
            name: ZMTX CPM binary
            path: ${{ github.workspace }}/ZMTX.COM
      - uses: actions/upload-artifact@v2
        with:
            name: ZMRX CPM binary
            path: ${{ github.workspace }}/ZMRX.COM
      - uses: actions/upload-artifact@v2
        with:
            name: ZMTX TOS binary
            path: ${{ github.workspace }}/build/zmtx.ttp
      - uses: actions/upload-artifact@v2
        with:
            name: ZMRX TOS binary
            path: ${{ github.workspace }}/build/zmrx.ttp
